/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ArbosTestInterface extends ethers.utils.Interface {
  functions: {
    "getAccountInfo(address)": FunctionFragment;
    "getMarshalledStorage(address)": FunctionFragment;
    "installAccount(address,bool,uint256,uint256,bytes,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAccountInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarshalledStorage",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "installAccount",
    values: [string, boolean, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAccountInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarshalledStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installAccount",
    data: BytesLike
  ): Result;

  events: {};
}

export class ArbosTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ArbosTestInterface;

  functions: {
    getAccountInfo(addr: string, overrides?: CallOverrides): Promise<[void]>;

    "getAccountInfo(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    getMarshalledStorage(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "getMarshalledStorage(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    installAccount(
      addr: string,
      isEOA: boolean,
      balance: BigNumberish,
      nonce: BigNumberish,
      code: BytesLike,
      initStorage: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "installAccount(address,bool,uint256,uint256,bytes,bytes)"(
      addr: string,
      isEOA: boolean,
      balance: BigNumberish,
      nonce: BigNumberish,
      code: BytesLike,
      initStorage: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getAccountInfo(addr: string, overrides?: CallOverrides): Promise<void>;

  "getAccountInfo(address)"(
    addr: string,
    overrides?: CallOverrides
  ): Promise<void>;

  getMarshalledStorage(addr: string, overrides?: CallOverrides): Promise<void>;

  "getMarshalledStorage(address)"(
    addr: string,
    overrides?: CallOverrides
  ): Promise<void>;

  installAccount(
    addr: string,
    isEOA: boolean,
    balance: BigNumberish,
    nonce: BigNumberish,
    code: BytesLike,
    initStorage: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "installAccount(address,bool,uint256,uint256,bytes,bytes)"(
    addr: string,
    isEOA: boolean,
    balance: BigNumberish,
    nonce: BigNumberish,
    code: BytesLike,
    initStorage: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getAccountInfo(addr: string, overrides?: CallOverrides): Promise<void>;

    "getAccountInfo(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getMarshalledStorage(
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "getMarshalledStorage(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    installAccount(
      addr: string,
      isEOA: boolean,
      balance: BigNumberish,
      nonce: BigNumberish,
      code: BytesLike,
      initStorage: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "installAccount(address,bool,uint256,uint256,bytes,bytes)"(
      addr: string,
      isEOA: boolean,
      balance: BigNumberish,
      nonce: BigNumberish,
      code: BytesLike,
      initStorage: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getAccountInfo(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getAccountInfo(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarshalledStorage(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getMarshalledStorage(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    installAccount(
      addr: string,
      isEOA: boolean,
      balance: BigNumberish,
      nonce: BigNumberish,
      code: BytesLike,
      initStorage: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "installAccount(address,bool,uint256,uint256,bytes,bytes)"(
      addr: string,
      isEOA: boolean,
      balance: BigNumberish,
      nonce: BigNumberish,
      code: BytesLike,
      initStorage: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAccountInfo(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAccountInfo(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarshalledStorage(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getMarshalledStorage(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    installAccount(
      addr: string,
      isEOA: boolean,
      balance: BigNumberish,
      nonce: BigNumberish,
      code: BytesLike,
      initStorage: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "installAccount(address,bool,uint256,uint256,bytes,bytes)"(
      addr: string,
      isEOA: boolean,
      balance: BigNumberish,
      nonce: BigNumberish,
      code: BytesLike,
      initStorage: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
