/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ArbSysInterface extends ethers.utils.Interface {
  functions: {
    "arbBlockNumber()": FunctionFragment;
    "arbOSVersion()": FunctionFragment;
    "getStorageAt(address,uint256)": FunctionFragment;
    "getTransactionCount(address)": FunctionFragment;
    "sendTxToL1(address,bytes)": FunctionFragment;
    "withdrawEth(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "arbBlockNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "arbOSVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStorageAt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "sendTxToL1",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "withdrawEth", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "arbBlockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "arbOSVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStorageAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sendTxToL1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEth",
    data: BytesLike
  ): Result;

  events: {
    "ERC20Withdrawal(address,address,uint256)": EventFragment;
    "ERC721Withdrawal(address,address,uint256)": EventFragment;
    "EthWithdrawal(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ERC20Withdrawal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ERC721Withdrawal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EthWithdrawal"): EventFragment;
}

export class ArbSys extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ArbSysInterface;

  functions: {
    arbBlockNumber(overrides?: CallOverrides): Promise<[BigNumber]>;

    "arbBlockNumber()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    arbOSVersion(overrides?: CallOverrides): Promise<[BigNumber]>;

    "arbOSVersion()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getStorageAt(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getStorageAt(address,uint256)"(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTransactionCount(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getTransactionCount(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    sendTxToL1(
      destAddr: string,
      calldataForL1: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "sendTxToL1(address,bytes)"(
      destAddr: string,
      calldataForL1: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    withdrawEth(
      dest: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "withdrawEth(address)"(
      dest: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  arbBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

  "arbBlockNumber()"(overrides?: CallOverrides): Promise<BigNumber>;

  arbOSVersion(overrides?: CallOverrides): Promise<BigNumber>;

  "arbOSVersion()"(overrides?: CallOverrides): Promise<BigNumber>;

  getStorageAt(
    account: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getStorageAt(address,uint256)"(
    account: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTransactionCount(
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getTransactionCount(address)"(
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  sendTxToL1(
    destAddr: string,
    calldataForL1: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "sendTxToL1(address,bytes)"(
    destAddr: string,
    calldataForL1: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  withdrawEth(
    dest: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "withdrawEth(address)"(
    dest: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    arbBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    "arbBlockNumber()"(overrides?: CallOverrides): Promise<BigNumber>;

    arbOSVersion(overrides?: CallOverrides): Promise<BigNumber>;

    "arbOSVersion()"(overrides?: CallOverrides): Promise<BigNumber>;

    getStorageAt(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getStorageAt(address,uint256)"(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTransactionCount(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTransactionCount(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sendTxToL1(
      destAddr: string,
      calldataForL1: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "sendTxToL1(address,bytes)"(
      destAddr: string,
      calldataForL1: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawEth(dest: string, overrides?: CallOverrides): Promise<void>;

    "withdrawEth(address)"(
      dest: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    ERC20Withdrawal(
      destAddr: string | null,
      tokenAddr: string | null,
      amount: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { destAddr: string; tokenAddr: string; amount: BigNumber }
    >;

    ERC721Withdrawal(
      destAddr: string | null,
      tokenAddr: string | null,
      id: BigNumberish | null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { destAddr: string; tokenAddr: string; id: BigNumber }
    >;

    EthWithdrawal(
      destAddr: string | null,
      amount: null
    ): TypedEventFilter<
      [string, BigNumber],
      { destAddr: string; amount: BigNumber }
    >;
  };

  estimateGas: {
    arbBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    "arbBlockNumber()"(overrides?: CallOverrides): Promise<BigNumber>;

    arbOSVersion(overrides?: CallOverrides): Promise<BigNumber>;

    "arbOSVersion()"(overrides?: CallOverrides): Promise<BigNumber>;

    getStorageAt(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getStorageAt(address,uint256)"(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTransactionCount(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTransactionCount(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sendTxToL1(
      destAddr: string,
      calldataForL1: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "sendTxToL1(address,bytes)"(
      destAddr: string,
      calldataForL1: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    withdrawEth(dest: string, overrides?: PayableOverrides): Promise<BigNumber>;

    "withdrawEth(address)"(
      dest: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    arbBlockNumber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "arbBlockNumber()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    arbOSVersion(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "arbOSVersion()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getStorageAt(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getStorageAt(address,uint256)"(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTransactionCount(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTransactionCount(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sendTxToL1(
      destAddr: string,
      calldataForL1: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "sendTxToL1(address,bytes)"(
      destAddr: string,
      calldataForL1: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    withdrawEth(
      dest: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "withdrawEth(address)"(
      dest: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
